steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - "build"
  - "--build-arg"
  - "cog_version=$_COG_VERSION"
  - "-t"
  - "us-central1-docker.pkg.dev/replicate/replicate-alpha/cog-director:$_COG_VERSION"
  - "-t"
  - "us-central1-docker.pkg.dev/replicate/replicate-alpha/cog-director:latest"
  - "."
images:
  - "us-central1-docker.pkg.dev/replicate/replicate-alpha/cog-director:$_COG_VERSION"
  - "us-central1-docker.pkg.dev/replicate/replicate-alpha/cog-director:latest"
logsBucket: "gs://replicate-cloudbuild"
